name: Lint and Format (using Prettier) on GitHub Pull Request from any feature branch to Main

on:
  pull_request:
    branches:
      - main

jobs:
  log-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build a Docker image
        run: docker build -t devops-hackathon .

      - name: Start a Docker container (based on the previously created image), then run linting and formatting on that container, and finally, stop the container
        run: docker run --rm devops-hackathon npm run lint && npm run format
