name: Simple Pull Request Logger

on:
  pull_request:
    branches:
      - main

jobs:
  log-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log a Message
        run: echo "Hello, a pull request has been made to the main branch!"
